
Unhandled error in evo.main_ape
Traceback (most recent call last):
  File "/home/eecs/roger_hsiao/.local/lib/python3.8/site-packages/evo/entry_points.py", line 94, in launch
    main_module.run(args)
  File "/home/eecs/roger_hsiao/.local/lib/python3.8/site-packages/evo/main_ape.py", line 205, in run
    result = ape(
  File "/home/eecs/roger_hsiao/.local/lib/python3.8/site-packages/evo/main_ape.py", line 160, in ape
    ape_metric.process_data(data)
  File "/home/eecs/roger_hsiao/.local/lib/python3.8/site-packages/evo/core/metrics.py", line 368, in process_data
    raise MetricsException(
evo.core.metrics.MetricsException: trajectories must have same number of poses

evo module evo.main_ape crashed - no logfile written (disabled)
